version: '3.1'

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
services:
  mongo:
    container_name: mongo
    image: mongo-local
    restart: always
    volumes:
      - mongo_data:/data/db
      - config_db:/data/configdb
    ports:
      - 27017:27017
    networks:
       network:
         ipv4_address: 172.30.0.2
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: kaginari.herokuapp.com
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    network_mode: host
    volumes:
    - "./conf/config.js:/node_modules/mongo-express/config.js:ro"
    depends_on:
      - mongo
volumes:
  mongo_data: {}
  config_db: {}
