#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-$HOME/.config/kaginari-mongodb-bot/github-app.env}"
mkdir -p "$(dirname "$ENV_FILE")"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "GitHub App for Kaginari/terraform-provider-mongodb"

# ── Stage 1: create the App ────────────────────────────────────────────────
stage "Create the GitHub App"
say "Kaginari is an organization (confirmed via the GitHub API), so the App must be"
say "created at the org level, not under your personal account."
open_url "https://github.com/organizations/Kaginari/settings/apps/new"
step "GitHub App name: pick something that reads clearly as automation, e.g."
step "  'kaginari-mongodb-bot' — this must be globally unique across all of GitHub,"
step "  so GitHub will tell you immediately if it's taken."
step "Homepage URL: paste https://github.com/Kaginari/terraform-provider-mongodb"
step "Webhook: UNCHECK 'Active' — no webhook needed for what we're using this for."
step "Scroll to 'Repository permissions' and set:"
step "  Contents        → Read and write"
step "  Issues          → Read and write"
step "  Pull requests   → Read and write"
step "  (Metadata read-only is included automatically)"
step "'Where can this GitHub App be installed?' → 'Only on this account'"
step "Click 'Create GitHub App' at the bottom."
say "After it's created, GitHub takes you to the App's settings page — the App ID"
say "is shown right at the top, under the App's icon/name."
ask GITHUB_APP_ID "Paste the App ID (a number):"
ask GITHUB_APP_NAME "Paste the exact App name you chose (needed for reference, not auth):"
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
write_env GITHUB_APP_NAME "$GITHUB_APP_NAME"

# ── Stage 2: private key ───────────────────────────────────────────────────
stage "Generate the private key"
say "Still on the App's settings page (if you navigated away, it's under"
say "Organization Settings → Developer settings → GitHub Apps → your app)."
step "Scroll down to 'Private keys'."
step "Click 'Generate a private key' — a .pem file downloads automatically."
step "Move it somewhere durable and NOT inside a git repo, e.g.:"
step "  mkdir -p ~/.config/github-apps && mv ~/Downloads/*.private-key.pem ~/.config/github-apps/"
warn "This file is a credential — treat it like a password. Never commit it."
ask GITHUB_APP_PRIVATE_KEY_PATH "Paste the full path where you saved the .pem file:"
if [[ ! -f "$GITHUB_APP_PRIVATE_KEY_PATH" ]]; then
  warn "That path doesn't exist yet — double check it once you've moved the file."
fi
write_env GITHUB_APP_PRIVATE_KEY_PATH "$GITHUB_APP_PRIVATE_KEY_PATH"

# ── Stage 3: install the App on the repo ───────────────────────────────────
stage "Install the App on the repo"
say "Back on the App's settings page, look at the left sidebar."
step "Click 'Install App'."
step "Next to the Kaginari organization, click 'Install'."
step "Choose 'Only select repositories', then pick 'terraform-provider-mongodb'."
step "Click 'Install'."
say "After installing, your browser lands on a URL that ends in a number, like:"
say "  https://github.com/organizations/Kaginari/settings/installations/12345678"
say "That trailing number is the Installation ID."
ask GITHUB_APP_INSTALLATION_ID "Paste the Installation ID (the number at the end of that URL):"
write_env GITHUB_APP_INSTALLATION_ID "$GITHUB_APP_INSTALLATION_ID"

# ── Stage 4: confirm everything is in place ────────────────────────────────
stage "Confirm"
say "Recorded so far:"
note "  App ID:            $GITHUB_APP_ID"
note "  App name:          $GITHUB_APP_NAME"
note "  Private key path:  $GITHUB_APP_PRIVATE_KEY_PATH"
note "  Installation ID:   $GITHUB_APP_INSTALLATION_ID"
say ""
say "That's everything needed. Claude will write a small script next that mints"
say "short-lived installation access tokens from the private key (the standard"
say "GitHub App auth flow: sign a JWT with the key, exchange it for a token"
say "scoped to this one installation) — no further manual steps after this."

finish
